# Change these first
owner: worldofsteelcraft # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Main Website
    url: https://worldofsteelcraft.tk
  - name: SMP Server
    url: $URL_SMPQUERYAPI
    showAverageResponseTime: false
    urlSecretText: SMP Server
  - name: WoSC Files
    url: https://files.worldofsteelcraft.tk
  - name: Link Service 1
    url: https://wosc.tk
  - name: Link Service 2
    url: https://lnksvc2.wosc.tk
  - name: Down Site Test 2
    url: $URL_DOWN_SITE_TEST
    showAverageResponseTime: false
    urlSecretText: Down Site Test 2

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.worldofsteelcraft.tk
  # baseUrl: /your-repo-name
  logoUrl: https://worldofsteelcraft.tk/images/logo.png
  name: World of SteelCraft
  introTitle: "World of SteelCraft Service Status"
  navbar:
    - title: Website
      href: https://worldofsteelcraft.tk
i18n:
  footer: "Copyright 2021-2022 by World of SteelCraft. Powered by [Upptime](https://github.com/upptime/upptime)"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
