owner: worldofsteelcraft 
repo: status
sites:
  - name: Main Website
    url: https://worldofsteelcraft.tk
  - name: SMP Server
    url: $URL_SMPQUERYAPI
    showAverageResponseTime: false
    urlSecretText: SMP Server
    __dangerous__body_down_if_text_missing: '"Online": true"'
  - name: WoSC Files
    url: https://files.worldofsteelcraft.tk
  - name: Link Service 1
    url: https://wosc.tk
  - name: Link Service 2
    url: https://lnksvc2.wosc.tk

status-website:
  cname: status.worldofsteelcraft.tk
  # baseUrl: /your-repo-name
  logoUrl: https://worldofsteelcraft.tk/images/logo.png
  name: World of SteelCraft
  introTitle: "World of SteelCraft Service Status"
  navbar:
    - title: Website
      href: https://worldofsteelcraft.tk
i18n:
  footer: "Copyright 2021-2023 by World of SteelCraft. Powered by [Upptime](https://github.com/upptime/upptime)"
